FROM ghcr.io/crytic/echidna/echidna:latest AS echidna

FROM ghcr.io/crytic/medusa:latest

COPY --from=echidna /usr/local/bin/forge /usr/local/bin/forge
COPY --from=echidna /usr/local/bin/cast /usr/local/bin/cast
COPY --from=echidna /usr/local/bin/anvil /usr/local/bin/anvil
COPY --from=echidna /usr/local/bin/chisel /usr/local/bin/chisel

ENV PATH="/usr/local/bin:/venv/bin:/usr/bin:/bin"
